
import com.jtattoo.plaf.fast.FastLookAndFeel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Haikal Al-Ghifari
 */
public class BeliTiket extends javax.swing.JFrame {

    /**
     * Creates new form Penyewaan
     */
    public BeliTiket() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

  
    int x = layar.width / 2  - this.getSize().width / 2;
    int y = layar.height / 2 - this.getSize().height / 2;

    this.setLocation(x, y);
    }
    protected void tema(){

        try{
                    /*
                     * Pada UIManager kalian bisa memilih jenis tema
                     * apa yang digunakan, sebagai contoh saya
                     * menggunakan tema BernsteinLookAndFeel
                    */
                    UIManager.setLookAndFeel(new FastLookAndFeel());
                }catch(UnsupportedLookAndFeelException ex){
                    ex.printStackTrace();
                }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jenisKendaraan = new javax.swing.JComboBox();
        hargaSewa = new javax.swing.JTextField();
        namaKendaraan = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("BELI TIKET");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Jenis Kendaraan");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Nama Kendaraan");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("Harga");

        jenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------------Pilih--------------", "Mobil", "Motor" }));
        jenisKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKendaraanActionPerformed(evt);
            }
        });

        hargaSewa.setEditable(false);

        namaKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKendaraanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hargaSewa)
                    .addComponent(namaKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenisKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sewa Kendaraan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MenuCustomer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKendaraanActionPerformed
        if(jenisKendaraan.getSelectedItem().equals("--------------Pilih--------------")){
            namaKendaraan.removeAllItems();
            namaKendaraan.setSelectedItem(null);
            
        }else if (jenisKendaraan.getSelectedItem().equals("Mobil")){
            namaKendaraan.removeAllItems();
            namaKendaraan.setSelectedItem(null);
            
            namaKendaraan.addItem("Avanza");
            namaKendaraan.addItem("Xenia");
            namaKendaraan.addItem("Agya");
            namaKendaraan.addItem("Jazz");
            namaKendaraan.addItem("Brio");
            
        }else if (jenisKendaraan.getSelectedItem().equals("Motor")){
            namaKendaraan.removeAllItems();
            namaKendaraan.setSelectedItem(null);
            
            namaKendaraan.addItem("Beat");
            namaKendaraan.addItem("Scoopy");
            namaKendaraan.addItem("Nmax");
            namaKendaraan.addItem("Supra");
            namaKendaraan.addItem("Kharisma");
        }
    }//GEN-LAST:event_jenisKendaraanActionPerformed

    private void namaKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKendaraanActionPerformed
        switch(namaKendaraan.getSelectedIndex()){
            case 0:
                if(jenisKendaraan.getSelectedItem().equals("Mobil")){
                    hargaSewa.setText("650000");
                } else
                hargaSewa.setText("250000");
                break;
            case 1:
                if(jenisKendaraan.getSelectedItem().equals("Mobil")){
                    hargaSewa.setText("550000");
                } else
                hargaSewa.setText("225000");
                break;
            case 2:
                if(jenisKendaraan.getSelectedItem().equals("Mobil")){
                    hargaSewa.setText("350000");
                } else
                hargaSewa.setText("300000");
                break;
            case 3:
                if(jenisKendaraan.getSelectedItem().equals("Mobil")){
                    hargaSewa.setText("400000");
                } else
                hargaSewa.setText("150000");
                break;
            case 4:
                if(jenisKendaraan.getSelectedItem().equals("Mobil")){
                    hargaSewa.setText("300000");
                } else
                hargaSewa.setText("100000");
                break;                
        }
    }//GEN-LAST:event_namaKendaraanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = 1;
        int j = 2;
        try{
            if(jenisKendaraan.getSelectedItem().equals("--------------Pilih--------------")){
            JOptionPane.showMessageDialog(this, "Harap Pilih Kendaraan");
            }else if(i < j){
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db10120709penyewaankendaraan_travel","root","");
                
                String query4 = "SELECT * FROM saldo, sesi WHERE saldo.user_id = sesi.user_id";
                PreparedStatement pst4 = con.prepareStatement(query4);
                ResultSet rs4 = pst4.executeQuery(query4);
                
                Statement st = con.createStatement();
                String sql = "SELECT * FROM tiket WHERE nama_kendaraan = '"+namaKendaraan.getSelectedItem()+"' AND status = 'Tersedia'";
                ResultSet rs = st.executeQuery(sql);
                
                String query2 = "SELECT * FROM saldo, sesi WHERE saldo.user_id = sesi.user_id";
                PreparedStatement pst2 = con.prepareStatement(query2);
                ResultSet rs2 = pst2.executeQuery(query2);
                
                 
                if (rs4.next()){
                    int Saldo = Integer.parseInt(rs4.getString("saldo"));
                    int Harga = Integer.parseInt(hargaSewa.getText());
                    if(Saldo < Harga){
                        JOptionPane.showMessageDialog(null, "Saldo Tidak Mencukupi");
                }else if                               
                    (rs.next()){
                    String KodeTiket = String.valueOf(rs.getString("kode_tiket"));
                    String Status = rs.getString("status");
                        
                    if("Tidak Tersedia".equals(Status)){
                        JOptionPane.showMessageDialog(null, "Tiket Kendaraan Habis");
                    }else if
                    (rs2.next()){
                    int tampung    = Integer.parseInt(hargaSewa.getText());
                    String saldo   = rs2.getString("saldo");                        
                    int info_saldo = Integer.parseInt(saldo);
                    int total      = info_saldo - tampung;
                    String ftotal  = String.valueOf(total);

                    String query5 = "UPDATE saldo, sesi SET saldo ='"+ftotal+"' WHERE saldo.user_id = sesi.user_id";
                    PreparedStatement pst5 = con.prepareStatement(query5);
                    pst5.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Tiket Berhasil Dibeli");
                    
                    String sqs = "UPDATE `sesi` SET `kode_tiket` = '"+ KodeTiket +"'";
                    PreparedStatement pst = con.prepareStatement(sqs);
                    pst.execute();
                    VerifikasiTiket vt = new VerifikasiTiket();
                    vt.show();
                    dispose();
                }                           
                }                
                }               
            }else {
                    
                    }
            
        }catch (Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        BeliTiket frame = new BeliTiket();
        frame.tema();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeliTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaSewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox jenisKendaraan;
    private javax.swing.JComboBox namaKendaraan;
    // End of variables declaration//GEN-END:variables
}
