import javax.swing.UIManager;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rijal
 */
public class BuatVoucher extends javax.swing.JFrame {

    /**
     * Creates new form TopUpSaldo
     */
    public BuatVoucher() {
        initComponents();
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();


            int x = posisi.width / 2  - this.getSize().width / 2;
            int y = posisi.height / 2 - this.getSize().height / 2;

            this.setLocation(x, y);
    }
        protected void tema(){
                try{
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                }catch(UnsupportedLookAndFeelException ex){
                    ex.printStackTrace();
                }
            }
        static String Kode(int n){
                String Kode = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                            + "0123456789"
                            + "abcdefghijklmnopqrstuvxyz";
                
                StringBuilder sb = new StringBuilder(n);
                    for (int i = 0; i < n; i++) {
                        int index
                        = (int)(Kode.length()
                            * Math.random());
                            sb.append(Kode.charAt(index));
                    }
        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nominalVoucher = new javax.swing.JComboBox<>();
        kodeVoucher = new javax.swing.JTextField();
        buatVoucher = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Nominal Voucher");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("Kode Voucher");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, -1, -1));

        nominalVoucher.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        nominalVoucher.setMaximumRowCount(5);
        nominalVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50000", "100000", "250000", "500000", "1000000" }));
        nominalVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalVoucherActionPerformed(evt);
            }
        });
        getContentPane().add(nominalVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 78, 301, -1));

        kodeVoucher.setEditable(false);
        kodeVoucher.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        getContentPane().add(kodeVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 301, -1));

        buatVoucher.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        buatVoucher.setText("Buat Voucher");
        buatVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatVoucherActionPerformed(evt);
            }
        });
        getContentPane().add(buatVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 162, -1, -1));

        kembali.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\1. Kuliah\\1.Unikom\\4. Semester 4\\4. Program Visual\\2. Tugas\\Tugas 5 Tugas Besar\\Background 500x270.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nominalVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalVoucherActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        TampilanAdmin tampilanadmin = new TampilanAdmin();
        tampilanadmin.show();
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void buatVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatVoucherActionPerformed
       
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db10120709penyewaankendaraan_travel","root","");
            String sql = "INSERT INTO `voucher` (`kode_voucher`,`nominal`,`status`) VALUES (?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            String selectedValue = nominalVoucher.getSelectedItem().toString();
            
            pst.setString(1, Kode(10));
            pst.setString(2, selectedValue);
            pst.setString(3, "Belum Digunakan");
            pst.execute();

            JOptionPane.showMessageDialog(this, "Voucher Berhasil Dibuat");        
        }catch (Exception e){
                System.out.print(e.getMessage());
            }
        
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db10120709penyewaankendaraan_travel","root","");
            Statement st = con.createStatement();
            String sql = "SELECT * FROM `voucher`";
            ResultSet rs = st.executeQuery(sql);
                
                while(rs.next()){
                    String KodeVoucher  = rs.getString("kode_voucher");
                    kodeVoucher.setText(KodeVoucher);
                    
                }            
        }catch (Exception e){
                System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_buatVoucherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        TampilanAdmin skin = new TampilanAdmin();
        skin.tema();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuatVoucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField kodeVoucher;
    private javax.swing.JComboBox<String> nominalVoucher;
    // End of variables declaration//GEN-END:variables
}
