
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rijal
 */
public class ManajemenVoucher extends javax.swing.JFrame {

    /**
     * Creates new form ManajemenVoucher
     */
    public ManajemenVoucher() {
        initComponents();
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();


            int x = posisi.width / 2  - this.getSize().width / 2;
            int y = posisi.height / 2 - this.getSize().height / 2;

            this.setLocation(x, y);
    }
    protected void tema(){
                try{
                    UIManager.setLookAndFeel(new GraphiteLookAndFeel());
                }catch(UnsupportedLookAndFeelException ex){
                    ex.printStackTrace();
                }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelVoucher = new javax.swing.JTable();
        refreshTable = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Voucher", "User Pengguna", "Kode Voucher", "Nominal", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelVoucher);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 830, -1));

        refreshTable.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        refreshTable.setText("Tampilkan Tabel");
        refreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTableActionPerformed(evt);
            }
        });
        getContentPane().add(refreshTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 456, -1, -1));

        kembali.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 760, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\1. Kuliah\\1.Unikom\\4. Semester 4\\4. Program Visual\\2. Tugas\\Tugas 5 Tugas Besar\\Background 850x800.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTableActionPerformed
        tabelVoucher.setModel(new DefaultTableModel(null,new String []{
        "ID Voucher","User Pengguna","Kode Voucher","Nominal","Status"}));
        
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db10120709penyewaankendaraan_travel","root","");
                
                Statement st = con.createStatement();
                String sql = "SELECT * FROM voucher";
                ResultSet rs = st.executeQuery(sql);                                
                
                while(rs.next()){
                    String IDVoucher  = rs.getString("id_voucher");
                    String UserPengguna = rs.getString("user_id");
                    String KodeVoucher = rs.getString("kode_voucher");
                    String Nominal = rs.getString("nominal");
                    String Status = String.valueOf(rs.getString("status"));
                    
                    String tbData[] = {IDVoucher,UserPengguna,KodeVoucher,Nominal,Status};
                    DefaultTableModel tblModel = (DefaultTableModel)tabelVoucher.getModel();
                    
                    tblModel.addRow(tbData);
                    
                }
                
                con.close();
            }catch (Exception e){
                System.out.print(e.getMessage());
            }
    }//GEN-LAST:event_refreshTableActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        TampilanAdmin tampilanadmin = new TampilanAdmin();
        tampilanadmin.show();
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ManajemenVoucher fitur = new ManajemenVoucher();
        fitur.tema();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenVoucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton refreshTable;
    private javax.swing.JTable tabelVoucher;
    // End of variables declaration//GEN-END:variables
}
